# Generated by Django 5.2.14 on 2026-05-14 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contact_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_content',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('tablet', 'Tablette'), ('desktop', 'Desktop')], max_length=10)),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('os', models.CharField(blank=True, max_length=80)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('landing_page', models.CharField(blank=True, max_length=500)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions analytiques',
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pageview', 'Page vue'), ('product_view', 'Vue produit'), ('add_to_cart', 'Ajout panier'), ('remove_from_cart', 'Retrait panier'), ('begin_checkout', 'Début checkout'), ('promo_applied', 'Code promo appliqué'), ('purchase', 'Achat'), ('signup', 'Inscription'), ('newsletter_subscribe', 'Abonnement newsletter'), ('wishlist_add', 'Ajout favoris'), ('search', 'Recherche')], db_index=True, max_length=30)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('universe', models.CharField(blank=True, max_length=10)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_oid', models.CharField(blank=True, max_length=20)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.analyticssession')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements analytiques',
                'ordering': ['-timestamp'],
            },
        ),
    ]
