# Generated by Django 5.2.14 on 2026-05-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_promo_universe_order_multipromo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomepromosettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
