# Generated by Django 5.2.14 on 2026-07-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_staff_push_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
