# Generated by Django 5.2.14 on 2026-08-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_product_references_and_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreference',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productreference',
            name='material',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productreference',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour garder le prix du produit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productreference',
            name='size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productreference',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Laisser vide pour ne pas suivre de stock séparé', null=True),
        ),
    ]
