# Generated by Django 5.2.14 on 2026-09-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_productreference_color_productreference_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbs/'),
        ),
    ]
